### ISSUE TITLE
Conflict registry containers when rerun workflow using "share image with cache"

### ISSUE THREAD

**Issue by kgkgzrtk** [yu-ichiro/setup-docker-compose-action#3]
In my project, after the first successful build using spin-up-docker-compose-actions, if I build the second job using cache, I get container conflicts. The optional parameters are not changed between the first and second jobs.

Should I delete the existing container and then rerun it?

### args
```yaml
     - name: Spin-Up Docker Compose
        uses: yu-ichiro/spin-up-docker-compose-action@v1.2
        with:
          file: docker-compose.yml
          shared: true
          bake: true
          push: true
          up: false
```

### actions log
```
Run [ "false" = "true" ]&&prefix="echo"; \
  [ "false" = "true" ]&&prefix="echo"; \
  $prefix docker run -d -p 5000:5000 --restart=always --name registry -v /tmp/docker-registry:/var/lib/registry registry:2; \
  $prefix npx wait-on tcp:5000
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env: ...
docker: Error response from daemon: Conflict. The container name "/registry" is already in use by container "46e73797bb98b70eefb1a3c0c13a9fac154d8cb1e3a0d449421693733c61320e". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
Error: Process completed with exit code 125.
```
